# Generated by Django 3.2.18 on 2023-06-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='nature',
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
